# Generated by Django 5.1.4 on 2024-12-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPB_NGI_pawnshop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
            ],
        ),
    ]
